name: PlayerTrackerr
version: '1.0.0'
main: dev.quacc.playertrackerr.PlayerTrackerr
api-version: '1.21.8'
api: spigot
author: QuaccOnCracc
softdepend:
  - "Vault"

commands:
  track:
    description: 'Track a player'
    permission: 'pt.command.track'
  playertracker:
    description: 'PlayerTracker main command'
    aliases:
      - 'pt'
  trackers:
    description: 'Open a menu showing all players currently tracking'
    permission: 'pt.trackers'
  cleartarget:
    description: 'Clear your own tracking or another players'
    aliases:
      - 'ct'
    permission: 'pt.cleartarget'
  giveptcompass:
    description: 'Give the configured PlayerTrackerr compass'
    aliases:
      - 'givecompass'
    permission: 'pt.givecompass'

permissions:
  pt.command.track:
    description: 'Allows using the /track command'
    default: op
  pt.compass:
    description: 'Allows starting tracking by right-clicking the configured compass item'
    default: op

  pt.givecompass:
    description: 'Allows giving the configured plugin compass via /giveptcompass'
    default: op


